version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

environment:
  matrix:
  - platform: x86
    generator: "Visual Studio 12 2013"
  - platform: x64
    generator: "Visual Studio 12 2013 Win64"

shallow_clone: true

before_build:
- mkdir build
- mkdir libepoxy-shared-%PLATFORM%
- set path=%path:C:\Python27;=%
- set path=%path:C:\Python27\Scripts;=%
- set path=%path%;C:\Python36;C:\Python36\Scripts
- mklink C:\Python36\python3.exe C:\Python36\python.exe
- cd build
- curl -LsSO https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip
- 7z x ninja-win.zip
- del ninja-win.zip
- curl -LsSO https://github.com/mesonbuild/meson/releases/download/0.38.0/meson-0.38.0.tar.gz
- 7z x meson-0.38.0.tar.gz
- move dist\meson-0.38.0.tar .
- 7z x meson-0.38.0.tar
- rmdir dist
- del meson-0.38.0.tar meson-0.38.0.tar.gz
- cd ..

build_script:
- cd build
- meson-0.38.0\meson.py .. . --backend vs2015
- msbuild /t:Rebuild /p:Configuration=Release libepoxy.sln
- cd ..

after_build:
- copy COPYING libepoxy-shared-%PLATFORM%
- 7z a -tzip libepoxy-shared-%PLATFORM%.zip libepoxy-shared-%PLATFORM%
- dir

artifacts:
  - path: libepoxy-shared-%PLATFORM%.zip
    name: libepoxy-shared-%PLATFORM%

test: off

deploy:
  release: libepoxy-shared-$(PLATFORM)
  description: "Epoxy (Windows $(PLATFORM))"
  provider: GitHub
  auth_token:
    secure: PF/wHCfSMFPCYyFh3GgjEJDHoPyPOnrmmbVMMwe8cNQBw2NL0vaYxjL1QcjMfpvL
  artifact: libepoxy-shared-$(PLATFORM)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
