version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

environment:
  matrix:
  - platform: x86
    config: Win32
    pout: x86
  - platform: x64
    config: x64
    pout: x64

shallow_clone: true

before_build:
- mkdir build
- mkdir libepoxy-shared-%pout%
- mkdir libepoxy-shared-%pout%\bin
- mkdir libepoxy-shared-%pout%\include
- mkdir libepoxy-shared-%pout%\include\epoxy
- mkdir libepoxy-shared-%pout%\lib
- cd build
- curl -LsSO https://github.com/mesonbuild/meson/releases/download/0.38.0/meson-0.38.0.tar.gz
- 7z x meson-0.38.0.tar.gz
- move dist\meson-0.38.0.tar .
- 7z x meson-0.38.0.tar
- rmdir dist
- del meson-0.38.0.tar meson-0.38.0.tar.gz
- cd ..

build_script:
- cd build
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
- C:\Python36\python.exe meson-0.38.0\meson.py .. . --backend=vs2015
- msbuild /t:Build /p:Configuration=debugoptimized /p:Platform=%config% libepoxy.sln
- cd ..

after_build:
- copy COPYING libepoxy-shared-%pout%
- xcopy include\epoxy\*.h libepoxy-shared-%pout%\include\epoxy /y
- xcopy build\include\epoxy\*.h libepoxy-shared-%pout%\include\epoxy /y
- copy build\src\epoxy-0.dll libepoxy-shared-%pout%\bin
- copy build\src\epoxy.lib libepoxy-shared-%pout%\lib
- dir libepoxy-shared-%pout% /s /b
- 7z a -tzip libepoxy-shared-%pout%.zip libepoxy-shared-%pout%

artifacts:
  - path: libepoxy-shared-%pout%.zip
    name: libepoxy-shared-%pout%

test: off

deploy:
  release: libepoxy-shared-$(pout)
  description: "Epoxy (Windows $(pout))"
  provider: GitHub
  auth_token:
    secure: PF/wHCfSMFPCYyFh3GgjEJDHoPyPOnrmmbVMMwe8cNQBw2NL0vaYxjL1QcjMfpvL
  artifact: libepoxy-shared-$(pout)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
