version: 1.0.{build}

image: Visual Studio 2013

configuration: Release

environment:
  matrix:
  - platform: x86
    outdir: Win32
  - platform: x64
    outdir: x64

shallow_clone: true

before_build:
- mkdir build
- mkdir install

build_script:
- cd build
- cmake .. -G "Visual Studio 12 2013 Win64" -DCMAKE_INSTALL_PREFIX=../install -DEPOXY_SUPPORT_EGL=OFF
- msbuild /t:Rebuild /p:Configuration=Release ALL_BUILD.vcxproj
- msbuild /t:Rebuild /p:Configuration=Release INSTALL.vcxproj
- cd ..

after_build:
- cd install
- dir
#- mkdir freetype-2.7.1-shared-%PLATFORM%
#- cd freetype-2.7.1-shared-%PLATFORM%
#- mkdir include
#- mkdir lib
#- mkdir bin
#- xcopy /e ..\freetype-2.7.1\include include
#- copy ..\freetype-2.7.1\objs\vc2010\%outdir%\freetype271.lib lib
#- copy ..\freetype-2.7.1\objs\vc2010\%outdir%\freetype271.exp lib
#- copy ..\freetype-2.7.1\objs\vc2010\%outdir%\freetype271.dll bin
#- cd ..
#- 7z a -ttar freetype-2.7.1-shared-%PLATFORM%.tar freetype-2.7.1-shared-%PLATFORM%
#- 7z a -tgzip freetype-2.7.1-shared-%PLATFORM%.tar.gz freetype-2.7.1-shared-%PLATFORM%.tar
#- del freetype-2.7.1-shared-%PLATFORM%.tar
#- dir

#artifacts:
#  - path: freetype-2.7.1-shared-$(PLATFORM).tar.gz
#    name: freetype-2.7.1-shared-$(PLATFORM)

test: off

#deploy:
#  release: freetype-2.7.1-shared-$(PLATFORM)
#  description: "FreeType 2.7.1 ($(PLATFORM))"
#  provider: GitHub
#  auth_token:
#    secure: PF/wHCfSMFPCYyFh3GgjEJDHoPyPOnrmmbVMMwe8cNQBw2NL0vaYxjL1QcjMfpvL
#  artifact: freetype-2.7.1-shared-$(PLATFORM)
#  draft: false
#  prerelease: false
#  on:
#    appveyor_repo_tag: true # deploy on tag push only
