version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

environment:
  matrix:
  - platform: x86
    generator: "Visual Studio 12 2013"
  - platform: x64
    generator: "Visual Studio 12 2013 Win64"

shallow_clone: true

before_build:
- mkdir build
- mkdir libepoxy-shared-%PLATFORM%
- python -V
- python3 -V
- ninja
- meson


build_script:
- cd build
- cmake .. -G "%generator%" -DCMAKE_INSTALL_PREFIX=../libepoxy-shared-%PLATFORM% -DEPOXY_SUPPORT_EGL=OFF
- msbuild /t:Rebuild /p:Configuration=Release ALL_BUILD.vcxproj
- msbuild /t:Rebuild /p:Configuration=Release INSTALL.vcxproj
- cd ..

after_build:
- copy COPYING libepoxy-shared-%PLATFORM%
- 7z a -tzip libepoxy-shared-%PLATFORM%.zip libepoxy-shared-%PLATFORM%
- dir

artifacts:
  - path: libepoxy-shared-%PLATFORM%.zip
    name: libepoxy-shared-%PLATFORM%

test: off

deploy:
  release: libepoxy-shared-$(PLATFORM)
  description: "Epoxy (Windows $(PLATFORM))"
  provider: GitHub
  auth_token:
    secure: PF/wHCfSMFPCYyFh3GgjEJDHoPyPOnrmmbVMMwe8cNQBw2NL0vaYxjL1QcjMfpvL
  artifact: libepoxy-shared-$(PLATFORM)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
