Document: libepoxy
Title: Debian libepoxy Manual
Author: <insert document author here>
Abstract: This manual describes what libepoxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libepoxy/libepoxy.sgml.gz

Format: postscript
Files: /usr/share/doc/libepoxy/libepoxy.ps.gz

Format: text
Files: /usr/share/doc/libepoxy/libepoxy.text.gz

Format: HTML
Index: /usr/share/doc/libepoxy/html/index.html
Files: /usr/share/doc/libepoxy/html/*.html
