name: macOS
on:
  push:
    branches-ignore:
      - debian
      - khronos-registry
jobs:
  build:
    strategy:
      matrix:
        build-opts:
          - ''
          - '-Dglx=no'
          - '-Degl=no'
          - '-Dx11=false'
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          brew install ninja
          python -m pip install --upgrade pip
          pip3 install meson
          /bin/sh -c "CC=clang .github/scripts/epoxy-ci-osx.sh ${{ matrix.build-opts }}"
