name: MSVC Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: "utf-8"
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v4
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: _build
        options: --verbose --fatal-meson-warnings
        meson-version: 1.2.2
